trikoder_oauth2:

  authorization_server:
    private_key: '%env(string:OAUTH2_PRIVATE_KEY_PATH)%'                     # Change this
    private_key_passphrase: null                            # Passphrase of the private key, if any

    encryption_key: '%env(string:OAUTH2_ENCRYPTION_KEY)%'   # (Optional) Change this

  resource_server:
    public_key: '%env(string:OAUTH2_PUBLIC_KEY_PATH)%'                       # Change this

  persistence:
    doctrine: null
