language: php
php:
  - 7.3

dist: bionic

git:
  depth: false

cache:
  yarn: true
  directories:
    - ".yarn"
    - "vendor"
    - "bin/.phpunit"

env:
  global:
    - SKIP_BUILD=`[[ $TRAVIS_COMMIT_MESSAGE == *"[skipbuild]"* ]]; echo $?`
    - APP_ENV=test

jobs:
  include:
    - name: Voer de phpunit tests uit
      install: |
        composer install
        yarn
        yarn production
      before_script: |
        php bin/console doctrine:database:create -n
        php bin/console doctrine:migrations:migrate -n
        php bin/console doctrine:fixtures:load -n
      script: php ./bin/phpunit
      if: type != pull_request OR fork = true
      addons:
        mariadb: '10.3'

script: skip
