# In deze map bevinden zich alleen maar .vue bestanden
---
parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
extends:
  - plugin:vue/vue3-recommended
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
rules:
  vue/multi-word-component-names: off
